### DISCUSSION TITLE
Neorg not working with Rocks.nvim

### DISCUSSION THREAD

**Discussion by salkin-mada** [nvim-neorg/neorg#1414] [Q&A]
Thank you so so so much for a wonderful tool. I use it everyday. It helps me in my wiki and note taking endeavors for code, music, math, memory, shell, linux, networking, electronics, hardware etc etc.

But after switching from Lazy.nvim to Rocks.nvim I actually have not been able to use Neorg.
What I noticed first while trying to get it to work (like described in the neorg README) was that my version was not up to date.

Why is the version not updated on luarocks? I cant get neorg to load/start with 8.4.0 and cant update to 8.4.1
I guess I should just get the latest via rocks-git, but then again its nice to just use luarocks.

note: as of this minute I have no idea if my trouble with getting neorg to work with rocks.nvim is related to the version or not.
I just came here as soon as I noticed my version being 8.4.0, while 8.4.1 is released.

**Comment by salkin-mada** [comment]
Switching to the rocks-git version (v8.4.1) didn't change a thing.
After `:lua require('neorg').setup()` I get nothing. No `:Neorg` commands. Nada.
I wonder if somethings buggy with my nvim 10 nightly.. Will try and rebuild newest commit.

**Reply by salkin-mada** [reply]
Okay I have narrowed it down to a Treesitter issue
```
Checking for errors while loading configs ~
- ERROR Error while loading config 'neorg.lua' for plugin 'neorg'.
  - ADVICE:
    - Error was: ...ua/neorg/modules/core/integrations/treesitter/module.lua:53: Unable to load nvim-treesitter.ts_utils 🙁
```
am I missing something in my Rocks toml?
```toml
[plugins]
"rocks.nvim" = "2.26.0"
"rocks-git.nvim" = "1.5.0"
"rocks-config.nvim" = "1.5.0"
"rocks-treesitter.nvim" = "scm"

... other plugins

[plugins.neorg]
git = "nvim-neorg/neorg"
rev = "v8.4.1"

[config]
plugins_dir = "plugins/"
auto_setup = false

[treesitter]
auto_install = "false"
auto_highlight = [
  "rust",
  "toml",
  "supercollider",
  "lua",
  "css",
  "html",
  "markdown",
  "norg",
  "cpp",
  "c",
  "json",
  "yaml",
  ]
```
