### ISSUE TITLE
tree-sitter-norg installs most of the time when nvim is run

### ISSUE THREAD

**Issue by redmaw** [nvim-neorg/neorg#1481]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0 Build type: RelWithDebInfo LuaJIT 2.1.1713773202

### Neorg setup

```lua
require("neorg").setup({
    load = {
        ["core.defaults"] = {},
        ["core.dirman"] = {
            config = {
                workspaces = {
                    notes = "~/Documents/notes"
                },
                default_workspace = "notes",
                index = "index.norg"
            }
        },
        ["core.concealer"] = {}
    }
})
```

### Actual behavior

tree-sitter-norg is downloaded and installed almost every time nvim is run.

![image](https://github.com/nvim-neorg/neorg/assets/17190361/e48dacd9-7e2e-4141-a4b0-7ff56c79dccd)

### Expected behavior

tree-sitter-norg is installed only once per version/rocks sync.

### Steps to reproduce

1. Install neorg via nvim.rocks.
2. Possibly install other plugins (see plugin section for details).
3. Open files with nvim. tree-sitter-norg should be installed most of the time during startup.

### Potentially conflicting plugins

```toml
# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.31.3"
"rocks-config.nvim" = "2.0.0"
"rocks-git.nvim" = "1.5.1"
neorg = "8.7.1"
"telescope.nvim" = "scm"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

[plugins.vim-commentary]
git = "tpope/vim-commentary"
rev = "v1.3^{}"

[plugins."telescope-ui-select.nvim"]
git = "nvim-telescope/telescope-ui-select.nvim"
branch = "master"
```

### Other information

Explicitly installing tree-sitter-norg (`Rocks install tree-sitter-norg`) doesn't appear to help.

### Help

No
